parameters:
    # request get params
    mell_rest_api.param_fields: _fields
    mell_rest_api.param_expands: _expands
    mell_rest_api.param_limit: _limit
    mell_rest_api.param_offset: _offset
    mell_rest_api.param_sort: _sort

    mell_rest_api:date_format: "Y-m-d"
    mell_rest_api:date_time_format: "Y-m-d:H:i:sZ"

    mell_rest_api:collection_key: "_collection"

services:
    mell_rest_api.request_manager:
        class: Mell\Bundle\RestApiBundle\Services\RequestManager
        arguments:
            - "@request_stack"
            - "%mell_rest_api.param_fields%"
            - "%mell_rest_api.param_expands%"
            - "%mell_rest_api.param_limit%"
            - "%mell_rest_api.param_offset%"
            - "%mell_rest_api.param_sort%"

    mell_rest_api.dto_manager:
        class: Mell\Bundle\RestApiBundle\Services\Dto\DtoManager
        arguments:
            - "@mell_rest_api.request_manager"
            - "@mell_rest_api.dto_validator"
            - "@mell_rest_api.dto_helper"
            - "@file_locator"
            - "@mell_rest_api.dto_manager_configurator"

    mell_rest_api.dto_validator:
        class: Mell\Bundle\RestApiBundle\Services\Dto\DtoValidator
        arguments: ["@mell_rest_api.dto_helper"]

    mell_rest_api.dto_manager_configurator:
        class: Mell\Bundle\RestApiBundle\Model\DtoManagerConfigurator
        arguments:
            - "%mell_rest_api.dto_config_path%"
            - "%mell_rest_api:collection_key%"
            - "%mell_rest_api:date_format%"
            - "%mell_rest_api:date_time_format%"

    mell_rest_api.dto_helper:
        class: Mell\Bundle\RestApiBundle\Helpers\DtoHelper