parameters:
    simple_dto.param_fields: "_fields"
    simple_dto.param_expands: "_expands"
    simple_dto.param_limit: "_limit"
    simple_dto.param_offset: "_offset"
    simple_dto.param_sort: "_sort"
    simple_dto.param_locale: "_locale"
    simple_dto.param_links: "_showLinks"
    simple_dto.header_locale: "Accept-Language"

    simple_dto.date_format: "Y-m-d"
    simple_dto.date_time_format: "c" # ISO 8601

    simple_dto.collection_key: "_collection"

    simple_dto.dto_config_path: "@AppBundle/Resources/config/dto/dto.yml"
    simple_dto.jwt_public_path: "%kernel.root_dir%/app/config/jwt_public.pem"

    simple_dto.hateoas_enabled: false


services:
    # DTO related services
    simple_dto.request_manager_configrator:
        class: Mell\Bundle\SimpleDtoBundle\Services\RequestManager\RequestManagerConfigurator
        arguments:
            - "%simple_dto.param_fields%"
            - "%simple_dto.param_expands%"
            - "%simple_dto.param_limit%"
            - "%simple_dto.param_offset%"
            - "%simple_dto.param_sort%"
            - "%simple_dto.param_locale%"
            - "%simple_dto.param_locale%"
            - "%simple_dto.param_links%"

    simple_dto.request_manager:
        class: Mell\Bundle\SimpleDtoBundle\Services\RequestManager\RequestManager
        arguments:
            - "@request_stack"
            - "@simple_dto.request_manager_configrator"

    simple_dto.dto_manager:
        class: Mell\Bundle\SimpleDtoBundle\Services\Dto\DtoManager
        arguments:
            - "@simple_dto.dto_validator"
            - "@simple_dto.dto_helper"
            - "@simple_dto.dto_manager_configurator"
            - "@event_dispatcher"

    simple_dto.dto_expands_manager:
        class: Mell\Bundle\SimpleDtoBundle\Services\Dto\DtoExpandsManager
        arguments:
            - "@simple_dto.dto_helper"

    simple_dto.dto_links_manager:
        class: Mell\Bundle\SimpleDtoBundle\Services\Dto\DtoLinksManager
        arguments:
            - "@security.expression_language"
            - "@router"
            - "@simple_dto.dto_helper"

    simple_dto.dto_validator:
        class: Mell\Bundle\SimpleDtoBundle\Services\Dto\DtoValidator
        arguments: ["@simple_dto.dto_helper"]

    simple_dto.dto_manager_configurator:
        class: Mell\Bundle\SimpleDtoBundle\Model\DtoManagerConfigurator
        arguments:
            - "%simple_dto.collection_key%"
            - "%simple_dto.date_format%"
            - "%simple_dto.date_time_format%"

    simple_dto.dto_helper:
        class: Mell\Bundle\SimpleDtoBundle\Helpers\DtoHelper
        arguments:
            - "@file_locator"
            - "%simple_dto.dto_config_path%"
            - "%simple_dto.date_format%"
            - "%simple_dto.date_time_format%"

    simple_dto.builder.links_builder:
        class: Mell\Bundle\SimpleDtoBundle\Services\Dto\Builder\LinksBuilder
        public: false
        arguments:
            - "@simple_dto.request_manager"
            - "@router"
            - "@security.expression_language"
            - "@simple_dto.dto_helper"
            - "@security.token_storage"
            - "@security.authentication.trust_resolver"
            - "@security.authorization_checker"
            - "@request_stack"
            - "%simple_dto.hateoas_enabled%"

        tags:
            - { name: simple_dto.dto_builder  }

    simple_dto.event_listener.expands_listener:
        class: Mell\Bundle\SimpleDtoBundle\EventListener\DtoExpandsListener
        arguments:
            - "@simple_dto.request_manager"
            - "@simple_dto.dto_helper"
            - "@simple_dto.dto_expands_manager"
        tags:
            - { name: kernel.event_listener, event: simple_dto.post_dto_encode, method: onPostDtoEncode }

    simple_dto.event_listener.links_listener:
        class: Mell\Bundle\SimpleDtoBundle\EventListener\DtoLinksListener
        arguments:
            - "@simple_dto.request_manager"
            - "@simple_dto.dto_links_manager"
            - "@simple_dto.dto_helper"
        calls:
            - ['setContainer', ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: simple_dto.post_dto_encode, method: onPostDtoEncode }

    # Security related services
    simple_dto.jwt_manager:
        class: Mell\Bundle\SimpleDtoBundle\Services\Jwt\JwtManager

    simple_dto.security.authenticator.api_key_authenticator:
        class: Mell\Bundle\SimpleDtoBundle\Security\Authenticator\ApiKeyAuthenticator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@simple_dto.jwt_manager"
            - "%simple_dto.jwt_public_path%"

    # Api docs related services
    simple_dto.doc.parser.dto_parser:
        class: Mell\Bundle\SimpleDtoBundle\Parser\ApiDocParser\DtoParser
        arguments:
            - "@simple_dto.dto_manager"
        tags:
            - { name: nelmio_api_doc.extractor.parser }

    simple_dto.doc.param_handler:
        class: Mell\Bundle\SimpleDtoBundle\Handler\ApiDocHandler\ApiDocHandler
        arguments:
            - "@simple_dto.request_manager_configrator"
            - "%simple_dto.hateoas_enabled%"
        tags:
            - { name: nelmio_api_doc.extractor.handler }