parameters:
    simple_dto.dto_config_path: "@AppBundle/Resources/config/dto/dto.yml"
    simple_dto.jwt_public_path: "%kernel.root_dir%/app/config/jwt_public.pem"
    simple_dto.auth_entity_alias: ~
    simple_dto.auth_username_fields: ~

services:
    # DTO related services
    simple_dto.request_manager_configurator:
        class: Mell\Bundle\SimpleDtoBundle\Services\RequestManager\RequestManagerConfigurator
        arguments:
            - "%simple_dto.param_fields%"
            - "%simple_dto.param_expands%"
            - "%simple_dto.param_limit%"
            - "%simple_dto.param_offset%"
            - "%simple_dto.param_sort%"
            - "%simple_dto.param_locale%"
            - "%simple_dto.header_locale%"
            - "%simple_dto.param_links%"
            - "%simple_dto.param_filters%"
            - "%simple_dto.param_count%"

    simple_dto.request_manager:
        class: Mell\Bundle\SimpleDtoBundle\Services\RequestManager\RequestManager
        arguments:
            - "@request_stack"
            - "@simple_dto.request_manager_configurator"

    simple_dto.dto_manager:
        class: Mell\Bundle\SimpleDtoBundle\Services\Dto\DtoManager
        arguments:
            - "@simple_dto.dto_validator"
            - "@simple_dto.dto_helper"
            - "@simple_dto.dto_manager_configurator"
            - "@simple_dto.request_manager_configurator"
            - "@event_dispatcher"

    simple_dto.api_filter_manager:
        class: Mell\Bundle\SimpleDtoBundle\Services\ApiFiltersManager\ApiFiltersManager

    simple_dto.dto_expands_manager:
        class: Mell\Bundle\SimpleDtoBundle\Services\Dto\DtoExpandsManager
        arguments:
            - "@simple_dto.dto_helper"
            - "@service_container"

    simple_dto.dto_links_manager:
        class: Mell\Bundle\SimpleDtoBundle\Services\Dto\DtoLinksManager
        arguments:
            - "@sensio_framework_extra.security.expression_language.default"
            - "@router"
            - "@simple_dto.dto_helper"

    simple_dto.dto_validator:
        class: Mell\Bundle\SimpleDtoBundle\Services\Dto\DtoValidator
        arguments: ["@simple_dto.dto_helper"]

    simple_dto.dto_manager_configurator:
        class: Mell\Bundle\SimpleDtoBundle\Model\DtoManagerConfigurator
        arguments:
            - "%simple_dto.collection_key%"
            - "%simple_dto.date_format%"
            - "%simple_dto.date_time_format%"

    simple_dto.dto_helper:
        class: Mell\Bundle\SimpleDtoBundle\Helpers\DtoHelper
        arguments:
            - "@file_locator"
            - "%simple_dto.dto_config_path%"
            - "%simple_dto.date_format%"
            - "%simple_dto.date_time_format%"

    simple_dto.event_listener.expands_listener:
        class: Mell\Bundle\SimpleDtoBundle\EventListener\DtoExpandsListener
        arguments:
            - "@simple_dto.request_manager"
            - "@simple_dto.dto_helper"
            - "@simple_dto.dto_expands_manager"
        tags:
            - { name: kernel.event_listener, event: simple_dto.post_dto_encode, method: onPostDtoEncode }
            - { name: kernel.event_listener, event: simple_dto.post_dto_collection_encode, method: onPostDtoCollectionEncode }

    simple_dto.event_listener.links_listener:
        class: Mell\Bundle\SimpleDtoBundle\EventListener\DtoLinksListener
        arguments:
            - "@simple_dto.request_manager"
            - "@simple_dto.dto_links_manager"
            - "@simple_dto.dto_helper"
        calls:
            - ['setContainer', ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: simple_dto.post_dto_encode, method: onPostDtoEncode }
            - { name: kernel.event_listener, event: simple_dto.post_dto_collection_encode, method: onPostDtoCollectionEncode }

    simple_dto.event_listener.api_filters_listener:
        class: Mell\Bundle\SimpleDtoBundle\EventListener\ApiFiltersListener
        arguments:
            - "@simple_dto.request_manager"
            - "@simple_dto.api_filter_manager"
            - "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    # Security related services
    simple_dto.jwt_manager:
        class: Mell\Bundle\SimpleDtoBundle\Services\Jwt\JwtManager
    simple_dto.security.provider.abstract_user_provider:
        class: Mell\Bundle\SimpleDtoBundle\Security\Provider\AbstractUserProvider
        abstract: true
        calls:
            - ['setJwtManager', ["@simple_dto.jwt_manager"]]
            - ['setPublicKeyPath', ["%simple_dto.jwt_public_path%"]]
    simple_dto.security.provider.bearer_client_provider:
        class: Mell\Bundle\SimpleDtoBundle\Security\Provider\BearerClientProvider
        parent: simple_dto.security.provider.abstract_user_provider
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%simple_dto.auth_entity_alias%"
            - "%simple_dto.auth_username_fields%"
    simple_dto.security.provider.trusted_client_provider:
        class: Mell\Bundle\SimpleDtoBundle\Security\Provider\TrustedClientProvider
        parent: simple_dto.security.provider.abstract_user_provider
        arguments:
            - "%simple_dto.trusted_clients%"

    simple_dto.security.authenticator.api_key_authenticator:
        class: Mell\Bundle\SimpleDtoBundle\Security\Authenticator\ApiKeyAuthenticator
        arguments:
            - ["@simple_dto.security.provider.bearer_client_provider", "@simple_dto.security.provider.trusted_client_provider"]
            - "%simple_dto.jwt_public_path%"

    # Api docs related services
    simple_dto.doc.parser.dto_parser:
        class: Mell\Bundle\SimpleDtoBundle\Parser\ApiDocParser\DtoParser
        arguments:
            - "@simple_dto.dto_manager"
        tags:
            - { name: nelmio_api_doc.extractor.parser }

    simple_dto.doc.param_handler:
        class: Mell\Bundle\SimpleDtoBundle\Handler\ApiDocHandler\ApiDocHandler
        arguments:
            - "@simple_dto.request_manager_configurator"
            - "%simple_dto.hateoas_enabled%"
        tags:
            - { name: nelmio_api_doc.extractor.handler }

    # Event listeners
    simple_dto.event_listener.trusted_client_access_listener:
        class: Mell\Bundle\SimpleDtoBundle\EventListener\TrustedClientAccessListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    simple_dto.event_listener.exception_listener:
        class: Mell\Bundle\SimpleDtoBundle\EventListener\ExceptionListener
        arguments:
            - "%kernel.environment%"
            - "%kernel.debug%"
        tags:
            - { name: kernel.event_listener, event: kernel.exception }