parameters:
    param_fields: "_fields"
    param_expands: "_expands"
    param_limit: "_limit"
    param_offset: "_offset"
    param_sort: "_sort"

    date_format: "Y-m-d"
    date_time_format: "c" # ISO 8601

    collection_key: "_collection"

    dto_config_path: "@AppBundle/Resources/config/dto/dto.yml"
    jwt_public_path: "%kernel.root_dir%/app/config/jwt_public.pem"

services:
    mell_rest_api.request_manager:
        class: Mell\Bundle\RestApiBundle\Services\RequestManager
        arguments:
            - "@request_stack"
            - "%mell_rest_api.param_fields%"
            - "%mell_rest_api.param_expands%"
            - "%mell_rest_api.param_limit%"
            - "%mell_rest_api.param_offset%"
            - "%mell_rest_api.param_sort%"

    mell_rest_api.dto_manager:
        class: Mell\Bundle\RestApiBundle\Services\Dto\DtoManager
        arguments:
            - "@mell_rest_api.request_manager"
            - "@mell_rest_api.dto_validator"
            - "@mell_rest_api.dto_helper"
            - "@mell_rest_api.dto_manager_configurator"

    mell_rest_api.dto_validator:
        class: Mell\Bundle\RestApiBundle\Services\Dto\DtoValidator
        arguments: ["@mell_rest_api.dto_helper"]

    mell_rest_api.dto_manager_configurator:
        class: Mell\Bundle\RestApiBundle\Model\DtoManagerConfigurator
        arguments:
            - "%mell_rest_api.dto_config_path%"
            - "%mell_rest_api.collection_key%"
            - "%mell_rest_api.date_format%"
            - "%mell_rest_api.date_time_format%"

    mell_rest_api.dto_helper:
        class: Mell\Bundle\RestApiBundle\Helpers\DtoHelper
        arguments:
            - "@file_locator"
            - "%mell_rest_api.dto_config_path%"

    mell_rest_api.jwt_manager:
        class: Mell\Bundle\RestApiBundle\Services\Jwt\JwtManager

    mell_rest_api.security.authenticator.api_key_authenticator:
        class: Mell\Bundle\RestApiBundle\Security\Authenticator\ApiKeyAuthenticator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@mell_rest_api.jwt_manager"
            - "%mell_rest_api.jwt_public_path%"
